#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=Run
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=02:00:00
#SBATCH --output=outputs/slurm_output_%A.out

#gpu_a100

module purge 
module load 2024
module load Anaconda3/2024.06-1

source $(conda info --base)/etc/profile.d/conda.sh

source activate mhcdiff

# wandb login

# srun python -u train.py --config /home/rhutter/MHC-Diff/configs/new_config.yml
# srun python -u test.py --config /home/rhutter/MHC-Diff/configs/new_config.yml


srun python -u train.py --config /home/rhutter/MHC-Diff/configs/flow_config.yml
# srun python -u test.py --config /home/rhutter/MHC-Diff/configs/flow_config.yml